/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.table_data.conf 15999 2007-03-25 22:32:02Z dts12 $
 */
#ifndef PCAPSNMPMONITORMIB_H
#define PCAPSNMPMONITORMIB_H

/* function declarations */
void init_pcapSnmpMonitorMIB(void);

/* column number definitions for table pcapFilterTable */
#define COLUMN_FLTINDEX		1
#define COLUMN_IFDESCR		2
#define COLUMN_FLTDESCR		3
#define COLUMN_FLTBPF		4
#define COLUMN_FLTPACKETS	5
#define COLUMN_FLTBYTES		6
#define COLUMN_FLTTERMINAL	7


#endif /* PCAPSNMPMONITORMIB_H */
